(* autogenerated from command-line-arguments *)
From Perennial.goose_lang Require Import prelude.

Section code.
Context `{ext_ty: ext_types}.
Local Coercion Var' s: expr := Var s.

Definition main: val :=
  rec: "main" <> :=
    let: "c" := ref_to (chanT boolT) (NewChan boolT #0) in
    Fork (ChannelSend (![chanT boolT] "c") #true);;
    let: "ret" := ref_to boolT (Fst (ChannelReceive (![chanT boolT] "c"))) in
    #().

End code.

From Perennial.goose_lang Require Import notation proofmode.
From Perennial.goose_lang.lib Require Import typed_mem.
From Perennial.goose_lang.lib Require Import control.
From Perennial.goose_lang.lib Require Export channel.
From Perennial.goose_lang Require Import notation typing.
From Perennial.goose_lang Require Import proofmode wpc_proofmode.
From Perennial.program_proof Require Import proof_prelude.

Section proof.
Context `{ffi_sem: ffi_semantics} `{!ffi_interp ffi} `{!heapGS Σ}.
Context {ext_ty: ext_types ext}.

Theorem ok :
  {{{ True }}} main #() {{{ RET #(); True }}}.
Proof.
  iIntros (Φ) "HP Post".
  unfold main.
  wp_call.
  wp_apply (channel.wp_NewChan _ _ _ (fun x => True)%I).
  { eauto. }
  iIntros (c chanref lk) "[#Hchan %Hc]".
  wp_pures.
  iDestruct (is_lock_ty with "Hchan") as "%".
  subst.
  wp_apply wp_ref_to.
  { eauto 10. }
  wp_pures.
  iIntros (c) "Hc".
  wp_pures.
  iMod (readonly_alloc_1 with "Hc") as "#Hc".
  wp_apply wp_fork.
  - wp_apply (wp_load_ro with "Hc").
    wp_apply (channel.wp_ChannelSend with "[Hchan]").
    { iFrame "Hchan". eauto. }
    done.
  - wp_pures.
    wp_apply (wp_load_ro with "Hc").
    wp_apply (channel.wp_ChannelReceive with "[Hchan]").
    { eauto. }
    iIntros (v ok).
    iIntros "[%Hv _]".
    wp_pures.
    wp_apply wp_ref_to.
    { eauto. }
    iIntros (ret) "Hret".
    wp_pures.
    iModIntro.
    iApply "Post".
    done.
Qed.