(* autogenerated from command-line-arguments *)
From Perennial.goose_lang Require Import prelude.

Section code.
Context `{ext_ty: ext_types}.
Local Coercion Var' s: expr := Var s.

Definition main: val :=
  rec: "main" <> :=
    let: "c" := ref (zero_val (chanT uint64T)) in
    "c" <-[chanT uint64T] NewChan uint64T #2;;
    Fork (ChannelSend (![chanT uint64T] "c") #1);;
    ChannelSend (![chanT uint64T] "c") #2;;
    let: "a" := ref (zero_val uint64T) in
    let: "b" := ref (zero_val uint64T) in
    let: "ok" := ref (zero_val boolT) in
    let: ("0_ret", "1_ret") := ChannelReceive (![chanT uint64T] "c") in
    "a" <-[uint64T] "0_ret";;
    "ok" <-[boolT] "1_ret";;
    (if: ![boolT] "ok"
    then control.impl.Assert ((![uint64T] "a" = #1) || (![uint64T] "a" = #2))
    else #());;
    let: ("0_ret", "1_ret") := ChannelReceive (![chanT uint64T] "c") in
    "b" <-[uint64T] "0_ret";;
    "ok" <-[boolT] "1_ret";;
    (if: ![boolT] "ok"
    then
      control.impl.Assert ((![uint64T] "b" = #1) || (![uint64T] "b" = #2));;
      #()
    else #()).

End code.

From Perennial.goose_lang Require Import notation proofmode.
From Perennial.goose_lang.lib Require Import typed_mem.
From Perennial.goose_lang.lib Require Import control.
From Perennial.goose_lang.lib Require Export channel.
From Perennial.goose_lang Require Import notation typing.
From Perennial.goose_lang Require Import proofmode wpc_proofmode.
From Perennial.program_proof Require Import proof_prelude.

Section proof.
Context `{ffi_sem: ffi_semantics} `{!ffi_interp ffi} `{!heapGS Σ}.
Context {ext_ty: ext_types ext}.

Theorem ok : 
  {{{ True }}} main #() {{{ RET #(); True }}}.
Proof.
  iIntros (Φ) "HP Post".
  unfold main.
  wp_call.
  wp_pures.
  wp_apply wp_ref_of_zero.
  { eauto. }
  iIntros (c) "Hc".
  wp_pures.
  wp_apply (channel.wp_NewChan _ _ _ (fun x => ⌜x = #1 ∨ x = #2⌝)%I).
  { eauto. }
  iIntros (cap chanref lk) "[#Hchan %Hc]".
  wp_pures.
  iDestruct (is_lock_ty with "Hchan") as "%".
  wp_apply (wp_StoreAt with "Hc").
  { unfold chanT. subst. eauto 10. }
  iIntros "Hc".
  wp_pures.
  iMod (readonly_alloc_1 with "Hc") as "#Hc".
  wp_apply wp_fork.
  - wp_apply (wp_load_ro with "Hc").
    rewrite Hc.
    wp_apply (channel.wp_ChannelSend with "[Hchan]").
    { iFrame "Hchan". eauto. }
    iIntros.
    done.
  - wp_pures.
    wp_apply (wp_load_ro with "Hc").
    rewrite Hc.
    wp_apply (channel.wp_ChannelSend with "[Hchan]").
    { iFrame "Hchan". eauto. }
    iIntros.
    wp_pures.
    wp_apply wp_ref_of_zero.
    { eauto. }
    iIntros (a) "Ha".
    wp_pures.
    wp_apply wp_ref_of_zero.
    { eauto. }
    iIntros (b) "Hb".
    wp_pures.
    wp_apply wp_ref_of_zero.
    { eauto. }
    iIntros (ok) "Hok".
    wp_pures.
    wp_apply (wp_load_ro with "Hc").
    wp_apply (channel.wp_ChannelReceive with "[Hchan]").
    { iFrame "Hchan". }
    iIntros (v open).
    iIntros "[%Hv Hbvalid]".
    wp_pures.
    wp_apply (wp_StoreAt with "Ha").
    { eauto. }
    iIntros "Ha".
    wp_pures.
    wp_store.
    wp_load.
    wp_if_destruct.
    + wp_load.
      iDestruct ("Hbvalid") as "%".
      destruct H0.
      { subst. wp_apply wp_Assert. { eauto. } wp_pures.
        wp_apply (wp_load_ro with "Hc").
        wp_apply (channel.wp_ChannelReceive with "[Hchan]").
        { iFrame "Hchan". }
        iIntros (v2 open2).
        iIntros "[%Hv2 Hdvalid]".
        wp_pures.
        wp_apply (wp_StoreAt with "Hb").
        { eauto. }
        iIntros "Hb".
        wp_pures.
        wp_store. 
        wp_load.
        wp_if_destruct.
        * wp_load.
          iDestruct ("Hdvalid") as "%".
          destruct H0.
          { subst. wp_pures. wp_apply wp_Assert. {eauto. } wp_pures. iModIntro. iApply "Post". done. }  
          subst.
          wp_pures.
          wp_load.
          wp_apply wp_Assert.
          { eauto. }
          wp_pures.
          iModIntro.
          iApply "Post".
          done.
        * iModIntro.
          iApply "Post".
          done. }
      subst.
      wp_pures.
      wp_load.
      wp_apply wp_Assert.
      { eauto. }
      wp_pures.
      wp_apply (wp_load_ro with "Hc").
      wp_apply (channel.wp_ChannelReceive with "[Hchan]").
      { iFrame "Hchan". }
      iIntros (v2 open2).
      iIntros "[%Hv2 Hdvalid]".
      wp_pures.
      wp_apply (wp_StoreAt with "Hb").
      { eauto. }
      iIntros "Hb".
      wp_pures.
      wp_store.
      wp_load.
      wp_if_destruct.
      * wp_load.
        iDestruct ("Hdvalid") as "%".
        destruct H0.
        { subst. wp_pures. wp_apply wp_Assert. {eauto. } wp_pures. iModIntro. iApply "Post". done. }
        subst.
        wp_pures.
        wp_load.
        wp_apply wp_Assert.
        { eauto. }
        wp_pures.
        iModIntro.
        iApply "Post".
        done.
      * iModIntro.
        iApply "Post".
        done.
    + wp_pures.
      wp_apply (wp_load_ro with "Hc").
      wp_apply (channel.wp_ChannelReceive with "[Hchan]").
      { iFrame "Hchan". }
      iIntros (v2 open2).
      iIntros "[%Hv2 Hdvalid]".
      wp_pures.
      wp_apply (wp_StoreAt with "Hb").
      { eauto. }
      iIntros "Hb".
      wp_pures.
      wp_apply (wp_StoreAt with "Hok").
      { eauto. }
      iIntros "Hok".
      wp_pures.
      wp_load.
      wp_if_destruct.
      * wp_load.
        iDestruct ("Hdvalid") as "%".
        destruct H0.
        { subst. wp_pures. wp_apply wp_Assert. {eauto. } wp_pures. iModIntro. iApply "Post". done. }
        subst.
        wp_pures.
        wp_load.
        wp_apply wp_Assert.
        { eauto. }
        wp_pures.
        iModIntro.
        iApply "Post".
        done.
      * iModIntro.
        iApply "Post".
        done.
Qed.